; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev, esp32pio
build_cache_dir = ~/.buildcache
extra_configs = 
	platformio_secret.ini

[common]
common_build_flags = 
	-D WIFI_SSID=\"${secret.wifi_ssid}\"
	-D WIFI_PASS=\"${secret.wifi_password}\"
	-D MQTT_BROKER_URL=\"${secret.mqtt_broker_url}\"
	-D MQTT_BROKER_PORT=${secret.mqtt_broker_port}
	-D MQTT_TOPIC=\"testTopic\"

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = ${common.common_build_flags}
board_build.mcu = esp32
lib_deps = knolleary/PubSubClient@^2.8

[env:esp32pio]
platform = espressif32
board = esp32-poe
framework = arduino
build_flags = ${common.common_build_flags}
board_build.mcu = esp32
lib_deps = knolleary/PubSubClient@^2.8

